stages:
  - deploy

deploy-to-server:
  stage: deploy
  image: thangnguyenduc1/ssh-image:latest
  tags:
    - devops
  variables:
    APP_DIR: "/home/ubuntu/src/vchatbot-web-app"
  script:
    - echo "Starting deployment to server $CHATBOTHOST_IP..."
    - |
      sshpass -p "$CHATBOTHOST_PASSWORD" ssh "$CHATBOTHOST_USER@$CHATBOTHOST_IP" "
        if [ -d "'$APP_DIR'" ]; then
          echo "Application directory found. Pulling latest code..."
          cd '$APP_DIR'
          git remote set-url origin https://'$GIT_USERNAME':'$GIT_PASSWORD'@git.vti.com.vn/vti-d3/ai/vti-chatbot/apps/vchatbot-web-app.git
          git pull origin dev
          echo "Stopping existing services..."
          docker compose down
        else
          echo "Application directory not found. Please clone the repository on the server first..."

        fi
        ls -al
        echo "Building and starting services with Docker Compose..."
        docker compose up --build -d
        echo "Deployment script finished."
      "
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"